apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    module: adapter
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-api
          image: {{ if .Values.dev }} {{ .Release.Name }} {{ else }} wdias/{{ .Release.Name }} {{ end }}
          imagePullPolicy: {{ if .Values.dev }} Never {{ else }} Always {{ end }}
          env:
            - name: APPNAME
              value: "api"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 128Mi
              cpu: 100m
        - name: {{ .Release.Name }}
          image: {{ if .Values.dev }} {{ .Release.Name }} {{ else }} wdias/{{ .Release.Name }} {{ end }}
          imagePullPolicy: {{ if .Values.dev }} Never {{ else }} Always {{ end }}
          env:
            - name: APPNAME
              value: "web"
          ports:
            - name: http2
              containerPort: 8082
              protocol: TCP
