apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    module: analysis
  namespace: default
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    module: analysis
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8082
      protocol: TCP
      name: http2
  selector:
    app: {{ .Release.Name }}
